app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Notepad, contact_schema, contacts_schema



api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'yee': 'haw'}
    
@api.route('/notepad', methods = ['POST'])
@token_required
def create_notepad(current_user_token):
    date = request.json['Date']
    note = request.json['Note']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    notepad = Notepad(date, note, user_token=user_token)

    db.session.add(notepad)
    db.session.commit()

    response = contact_schema.dump(notepad)
    return jsonify(response) 

@api.route('/notepad', methods = ['GET'])
@token_required
def get_notepad(current_user_token):
    a_user = current_user_token.token
    notepad = Notepad.query.filter_by(user_token = a_user).all()
    response = contacts_schema.dump(notepad)
    return jsonify(response)

@api.route('/notepad/<id>', methods = ['GET'])
@token_required
def get_single_notepad(current_user_token, id):
    notepad = Notepad.query.get(id)
    response = contact_schema.dump(notepad)
    return jsonify(response)

@api.route('/notepad/<id>', methods = ['POST', 'PUT'])
@token_required
def update_notepad(current_user_token, id):
    notepad = Notepad.query.get(id)
    notepad.date = request.json['Date']
    notepad.note = request.json['Note']
    notepad.user_token = current_user_token.token

    db.session.commit()
    response = contact_schema.dump(notepad)
    return jsonify(response)

@api.route('/notepad/<id>', methods = ['DELETE'])
@token_required
def delete_notepad(current_user_token, id):
    notepad = Notepad.query.get(id)
    db.session.delete(notepad)
    db.session.commit()
    response = contact_schema.dump(notepad)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
     if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        user = User(email, password = password)

        db.session.add(user)
        db.session.commit()

        flash(f'You have successfuly created a user account {email}', 'User-created')
        return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form = form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('You have failed your attempt to access this content,', 'auth-failed')
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_in.html', form = form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Inventory</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">Car Inventory</a>
            <button
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>